<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>s</string>
		<string>$C</string>
	</array>
	<key>name</key>
	<string>TASM_6502 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
		<key>comment</key>
			<string>TASM Directives</string>
			<key>match</key>
			<string>(?i)(\b(ADDINSTR|AVSYM|BASIC|CHK|CODES|NOCODES|DEFINE|DEFCONT|ECHO|EJECT|ELSE|END|ENDIF|EQU|EXPORT|FILL|IFDEF|IFNDEF|IF|INCLUDE|LIST|NOLIST|LOCALLABELCHAR|LSFIRST|MSFIRST|MODULE|ORG|PAGE|NOPAGE|SET|SYM|AVSYM|TEST|TITLE)\b)</string>
			<key>name</key>
			<string>keyword.control.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Asm data definition directives</string>
			<key>match</key>
			<string>(?i)(\b(block|bseg|cseg|dseg|nseg|xseg|byte|db|dw|word)\b)</string>
			<key>name</key>
			<string>storage.type.datadef.asm</string>
		</dict>
		<dict>
		<key>comment</key>
			<string>Flags</string>
			<key>match</key>
			<string>\b(S|Z|AC|P|CY)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single-line string</string>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single-line string</string>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>8085 Mnemonics</string>
			<key>match</key>			
			<string>(?i)(\b(ADC|AND|ASL|BCC|BCS|BEQ|BNE|BMI|BPL|BVC|BVS|BIT|BRK|CLC|CLD|CLI|CLV|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JSR|LDA|LDX|LDY|LSR|NOP|ORA|PHA|PHP|PLA|PLP|ROL|ROR|RTI|RTS|SBC|SEC|SED|SEI|STA|STX|STY|TAX|TAY|TSX|TXA|TXS|TYA|STZ|TRB|TSB|BRA|BBR0|BBR1|BBR2|BBR3|BBR4|BBR5|BBR6|BBR7|BBS0|BBS1|BBS2|BBS3|BBS4|BBS5|BBS6|BBS7|MUL|PHX|PHY|PLX|PLY|RMB0|RMB1|RMB2|RMB3|RMB4|RMB5|RMB6|RMB7|SMB0|SMB1|SMB2|SMB3|SMB4|SMB5|SMB6|SMB7)\b)</string>
			<key>name</key>
			<string>keyword.mnemonic.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\d{5}</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
		<key>comment</key>
			<string>8 bit register set</string>
			<key>match</key>
			<string>(?i)(\b(a|x|y|p|s)\b)</string>
			<key>name</key>
			<string>variable.parameter.register.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>16 bit register set</string>
			<key>match</key>
			<string>(?i)(\baf')|(\b(sp|pc)\b)</string>
			<key>name</key>
			<string>variable.parameter.register.asm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>HEX/DEC/BIN number</string>
			<key>match</key>
			<string>(?i)(%[01]+\b)|(\b[01]+b\b)|((#|\$)[0-9a-f]+\b)|(\b([0-9]+|0x[0-9a-f]+|[0-9][0-9a-f]*h)\b)</string>
			<key>name</key>
			<string>constant.numeric.asm</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.tasm6502</string>
	<key>uuid</key>
	<string>5075ff92-54a7-11e6-beb8-9e71128cafff</string>
</dict>
</plist>
